### ISSUE TITLE
Error if database is not manually created

### ISSUE THREAD

**Issue by rEnr3n** [fossar/selfoss#1026]
OS: ArchLinux ARM
Database: Postgresql 10.3
PHP 7.2.3

config.ini
```
[globals]
db_type=pgsql
db_host=localhost
db_database=selfoss
db_username=so
db_password=
```

Docs says the database will be created automatically. It did not in my case. I just got this error.

```
[2018-03-14 13:03:22] selfoss.ERROR: SQLSTATE[08006] [7] FATAL:  database "selfoss" does not exist {"exception":"[object] (PDOException(code: 7): SQLSTATE[08006] [7] FATAL:  database \"selfoss\" does not exist at /usr/share/webapps/selfoss/vendor/bcosca/fatfree-core/db/sql.php:519)
[stacktrace]
#0 /usr/share/webapps/selfoss/vendor/bcosca/fatfree-core/db/sql.php(519): PDO->__construct('pgsql:host=loca...', 'so', '', Array)
#1 /usr/share/webapps/selfoss/daos/pgsql/Database.php(45): DB\\SQL->__construct('pgsql:host=loca...', 'so', '')
#2 /usr/share/webapps/selfoss/daos/Database.php(25): daos\\pgsql\\Database->__construct()
#3 /usr/share/webapps/selfoss/daos/Sources.php(26): daos\\Database->__construct()
#4 /usr/share/webapps/selfoss/controllers/Sources.php(111): daos\\Sources->__construct()
#5 /usr/share/webapps/selfoss/controllers/Sources.php(241): controllers\\Sources->sourcesListAsString()
#6 /usr/share/webapps/selfoss/vendor/bcosca/fatfree-core/base.php(1806): controllers\\Sources->sourcesStats(Object(Base), Array, 'controllers\\\\Sou...')
#7 /usr/share/webapps/selfoss/vendor/bcosca/fatfree-core/base.php(1627): Base->call(Array, Array, Array)
#8 /usr/share/webapps/selfoss/index.php(80): Base->run()
#9 {main}
"}
```

I had to create the database manually to fix it.

**Comment by jtojnar** [comment]
It means the database content (tables, triggers, etc.) will be created automatically, web apps should not really have permissions to create databases. I guess we should find less ambiguous description.

**Comment by rEnr3n** [comment]
I see. I thought it meant the database itself because I know other projects create it automatically.

**Comment by jtojnar** [comment]
I have clarified the installation docs around this: https://selfoss.aditu.de/docs/administration/installation/basic/
