### ISSUE TITLE
Crash when parsing HTTP content-security-policy header

### ISSUE THREAD

**Issue by flozz** [fossar/selfoss#1332]
Hello,

I am trying to add an RSS feed to my Selfoss but it is not able to read it: it crashes when parsing HTTP content-security-policy headers.

**Versions:**

* **Selfoss:** Latest commit on `master` (70a9f2d)
* **PHP:** 8.1.4 

**The feed:**

*  https://lehollandaisvolant.net/rss.php

**The HTTP header that causes the crash:**

```
content-security-policy: default-src 'self' 'unsafe-inline'; img-src 'self' * data:; script-src 'self' 'unsafe-inline'; frame-ancestors 'none'; base-uri 'self'; form-action 'self' https://www.matronix.fr; frame-src https://www.youtube.com
```

**The log generated:**

```
[2022-04-09 09:43:57] selfoss.ERROR: error loading feed content for Le Hollandais Volant {"exception":"[object] (InvalidArgumentException(code: 0): \"default-src 'self' 'unsafe-inline'; img-src 'self' * data:; script-src 'self' 'unsafe-inline'; frame-ancestors 'none'; base-uri 'self'; form-action 'self' https://www.matronix.fr; frame-src https://www.youtube.com\" is not valid header value at /home/sites/selfoss/selfoss-2.19-70a9f2d/vendor/guzzlehttp/psr7/src/MessageTrait.php:267)
[stacktrace]
#0 [...]/selfoss-2.19-70a9f2d/vendor/guzzlehttp/psr7/src/MessageTrait.php(203): GuzzleHttp\\Psr7\\Response->assertValue()
#1 [internal function]: GuzzleHttp\\Psr7\\Response->GuzzleHttp\\Psr7\\{closure}()
#2 [...]/selfoss-2.19-70a9f2d/vendor/guzzlehttp/psr7/src/MessageTrait.php(206): array_map()
#3 [...]/selfoss-2.19-70a9f2d/vendor/guzzlehttp/psr7/src/MessageTrait.php(175): GuzzleHttp\\Psr7\\Response->trimAndValidateHeaderValues()
#4 [...]/selfoss-2.19-70a9f2d/vendor/guzzlehttp/psr7/src/MessageTrait.php(148): GuzzleHttp\\Psr7\\Response->normalizeHeaderValue()
#5 [...]/selfoss-2.19-70a9f2d/vendor/guzzlehttp/psr7/src/Response.php(107): GuzzleHttp\\Psr7\\Response->setHeaders()
#6 [...]/selfoss-2.19-70a9f2d/vendor/guzzlehttp/guzzle/src/Handler/EasyHandle.php(81): GuzzleHttp\\Psr7\\Response->__construct()
#7 [...]/selfoss-2.19-70a9f2d/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(565): GuzzleHttp\\Handler\\EasyHandle->createResponse()
#8 [internal function]: GuzzleHttp\\Handler\\CurlFactory->GuzzleHttp\\Handler\\{closure}()
#9 [...]/selfoss-2.19-70a9f2d/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(40): curl_exec()
#10 [...]/selfoss-2.19-70a9f2d/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\\Handler\\CurlHandler->__invoke()
#11 [...]/selfoss-2.19-70a9f2d/vendor/fossar/guzzle-transcoder/src/GuzzleTranscoder.php(81): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}()
#12 [...]/selfoss-2.19-70a9f2d/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(37): Fossar\\GuzzleTranscoder\\GuzzleTranscoder->Fossar\\GuzzleTranscoder\\{closure}()
#13 [...]/selfoss-2.19-70a9f2d/vendor/guzzlehttp/guzzle/src/Middleware.php(29): GuzzleHttp\\PrepareBodyMiddleware->__invoke()
#14 [...]/selfoss-2.19-70a9f2d/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(70): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}()
#15 [...]/selfoss-2.19-70a9f2d/vendor/guzzlehttp/guzzle/src/Middleware.php(59): GuzzleHttp\\RedirectMiddleware->__invoke()
#16 [...]/selfoss-2.19-70a9f2d/vendor/guzzlehttp/guzzle/src/HandlerStack.php(71): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}()
#17 [...]/selfoss-2.19-70a9f2d/vendor/guzzlehttp/guzzle/src/Client.php(351): GuzzleHttp\\HandlerStack->__invoke()
#18 [...]/selfoss-2.19-70a9f2d/vendor/guzzlehttp/guzzle/src/Client.php(162): GuzzleHttp\\Client->transfer()
#19 [...]/selfoss-2.19-70a9f2d/vendor/guzzlehttp/guzzle/src/Client.php(182): GuzzleHttp\\Client->requestAsync()
#20 [...]/selfoss-2.19-70a9f2d/vendor/guzzlehttp/guzzle/src/Client.php(95): GuzzleHttp\\Client->request()
```

**Comment by jtojnar** [comment]
Thanks for reporting, looks like it has been fixed in https://github.com/guzzle/psr7/compare/1.8.4...1.8.5.

**Comment by flozz** [comment]
Wow so quick!

I just tested with upgraded `guzzlehttp/psr7` version, and it works now. Thank you! :)
