### ISSUE TITLE
ReaderForSelfoss broke

### ISSUE THREAD

**Issue by cmm** [fossar/selfoss#1508]
[ I realize this is not technically the right place to report issues with 3rd-party clients, but also kind of is because there is no other (working) outlet to do so at present, and this specific client is currently linked from the Selfoss home page, so ]

The breakage itself is inability to log in to the Selfoss instance, but something bigger and fishy-looking seems to be going on:

- The latest build on F-Droid, at the time of writing this, is `124113311-github` ("-github"?).  The corresponding source tarball is `https://f-droid.org/repo/bou.amine.apps.readerforselfossv2.android_124113311_src.tar.gz`.
- The tarball is downloadable, and `v124113311` exists on "releases" page (the tarball linked from there is different from the one used by F-Droid, but source code therein seems identical apart from some Gradle stuff), but there are no commits in the repository, reachable from the release tag, that correspond to the (quite non-trivial) changelog of the F-Droid build.  In fact, `CHANGELOG.md` on both the `master` branch and the `v124113311` tag ends at the _previous_ release (`v124113301`).  On the `release` branch it does end on `v124113311`, but with a trivial chore-only list of changes.
- You need to register on the site to report an issue at the supposedly-correct place, but the registration flow is broken: confirmation e-mails are never sent.  Which is why I'm reporting here.

FYI to anyone affected, I guess.

**Comment by jtojnar** [comment]
Thanks for reporting.

What selfoss and Android version do you use? Are there any errors or will the app just crash? Are you able to get Android logs (e.g. by running `adb logcat` command on your computer after enabling USB debugging on your phone)?

I just tried running the version `124113311-github` on my old Android 13 phone but that crashes for me immediately after the main activity opens. I opened an issue for that: https://gitea.amine-bouabdallaoui.fr/Louvorg/ReaderForSelfoss-multiplatform/issues/166


> * The latest build on F-Droid, at the time of writing this, is `124113311-github` ("-github"?).  The corresponding source tarball is `https://f-droid.org/repo/bou.amine.apps.readerforselfossv2.android_124113311_src.tar.gz`.

I think that is just a remnant from the time the project used GitHub.

> * The tarball is downloadable, and `v124113311` exists on "releases" page (the tarball linked from there is different from the one used by F-Droid, but source code therein seems identical apart from some Gradle stuff)

I think that is just the tarball auto-generated by Gitea from the repo. At least GitHub does the same thing.

> but there are no commits in the repository, reachable from the release tag, that correspond to the (quite non-trivial) changelog of the F-Droid build.  In fact, `CHANGELOG.md` on both the `master` branch and the `v124113311` tag ends at the _previous_ release (`v124113301`).  On the `release` branch it does end on `v124113311`, but with a trivial chore-only list of changes.

Looking at the [commit log](https://gitea.amine-bouabdallaoui.fr/Louvorg/ReaderForSelfoss-multiplatform/commits/branch/master), all of the last few changelogs have been only updated after the corresponding version was released. Perhaps this is a limitation of the automatic Fastlane workflow.

Anyway, you can get the changes by comparing the tags directly https://gitea.amine-bouabdallaoui.fr/Louvorg/ReaderForSelfoss-multiplatform/compare/v124113301...v124113311

> * You need to register on the site to report an issue at the supposedly-correct place, but the registration flow is broken: confirmation e-mails are never sent.  Which is why I'm reporting here.

cc @aminecmi

**Comment by cmm** [comment]
> What selfoss and Android version do you use?

Selfoss is 2.19 + #1487.  Android is stock Xiomi HyperOS on a Redmi Note 13 Something, so Android 14 plus some gunk (I don't root phones any more, life's too short and Google Pay is too convenient. Pretty sure Xiaomi is not to blame this time, though)

> I just tried running the version 124113311-github on my old Android 13 phone but that crashes for me immediately after the main activity opens.

Or right, the same happens for me if I upgrade from the previous version of the app.  Failure to login is something that happens after you clean the app data (I'll post _those_ logs in another comment).  Here is the log for the same crash on startup that you are probably experiencing:

```
12-07 17:57:17.109 22650 22650 E AndroidRuntime: FATAL EXCEPTION: main
12-07 17:57:17.109 22650 22650 E AndroidRuntime: Process: bou.amine.apps.readerforselfossv2.android, PID: 22650
12-07 17:57:17.109 22650 22650 E AndroidRuntime: w2.e: Illegal input: The name of serial descriptor should uniquely identify associated serializer.
12-07 17:57:17.109 22650 22650 E AndroidRuntime: For serial name b there already exist BSerializer.
12-07 17:57:17.109 22650 22650 E AndroidRuntime: Please refer to SerialDescriptor documentation for additional information.
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at x2.c.a(SourceFile:253)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at w2.d$a$a.a(SourceFile:78)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at r3.f$a.b(SourceFile:87)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at w2.d$a.b(SourceFile:14)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at r3.k.a(SourceFile:79)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at r3.e.g(SourceFile:1)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at w2.d.a(SourceFile:84)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at a2.b.c(SourceFile:270)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at a2.b$b$b.B(SourceFile:130)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at a2.b$b$b.E(SourceFile:14)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at a2.b$b$b.i(SourceFile:7)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at G2.n.o(SourceFile:48)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at G2.n.f(SourceFile:24)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at Q1.a$d.B(SourceFile:41)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at Q1.a$d.E(SourceFile:12)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at Q1.a$d.i(SourceFile:7)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at G2.n.o(SourceFile:48)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at G2.n.f(SourceFile:24)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at c2.f$g.B(SourceFile:102)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at c2.f$g.E(SourceFile:12)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at c2.f$g.i(SourceFile:7)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at G2.n.o(SourceFile:48)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at G2.n.f(SourceFile:24)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at G2.n.h(SourceFile:4)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at W1.g$a$b.B(SourceFile:57)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at W1.g$a$b.E(SourceFile:14)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at W1.g$a$b.i(SourceFile:7)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at G2.n.o(SourceFile:48)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at G2.n.f(SourceFile:24)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at G2.n.b(SourceFile:20)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at G2.d.d(SourceFile:9)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at R1.b.b(SourceFile:179)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at v0.e.h(SourceFile:242)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at v0.e$a.B(SourceFile:12)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at V2.a.l(SourceFile:12)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at o3.a0.run(SourceFile:129)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:958)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:224)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:318)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8765)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	Suppressed: t3.i: [T0{Cancelling}@9cda0, Dispatchers.Main]
12-07 17:57:17.109 22650 22650 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: The name of serial descriptor should uniquely identify associated serializer.
12-07 17:57:17.109 22650 22650 E AndroidRuntime: For serial name b there already exist BSerializer.
12-07 17:57:17.109 22650 22650 E AndroidRuntime: Please refer to SerialDescriptor documentation for additional information.
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at F3.D0.d(SourceFile:105)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at F3.D0.a(SourceFile:11)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at D3.i.a(SourceFile:17)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at t0.e.a(SourceFile:5)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at C3.a.u(SourceFile:6)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at t0.c$a.b(SourceFile:3)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at F3.w0$b.a(SourceFile:9)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at F3.w0$b.d(SourceFile:1)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at P2.s.getValue(SourceFile:12)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at F3.w0.q(SourceFile:3)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at F3.w0.k(SourceFile:1)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at D3.h$a.b(SourceFile:14)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at D3.h$a.next(SourceFile:1)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at F3.x0.a(SourceFile:43)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at F3.w0$a.a(SourceFile:7)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at F3.w0$a.d(SourceFile:1)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at P2.s.getValue(SourceFile:12)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at F3.w0.s(SourceFile:3)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at F3.w0.hashCode(SourceFile:1)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at H3.y.a(SourceFile:13)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at H3.y.b(SourceFile:16)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at H3.J.d(SourceFile:22)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at H3.J.h(SourceFile:1)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at H3.J.g(SourceFile:38)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at H3.Y.O(SourceFile:28)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at H3.Y.G(SourceFile:27)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at t0.c$a.f(SourceFile:45)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at t0.c$a.e(SourceFile:1)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at H3.Y.k(SourceFile:78)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at E3.a.I(SourceFile:6)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at E3.a.v(SourceFile:33)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at t0.d$a.f(SourceFile:75)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at t0.d$a.e(SourceFile:1)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at H3.Y.k(SourceFile:78)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at G3.b.c(SourceFile:31)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	at x2.c.a(SourceFile:191)
12-07 17:57:17.109 22650 22650 E AndroidRuntime: 	... 43 more
```

**Comment by cmm** [comment]
[ ... continued ]

Now, if you clear all app data and start the app again, it starts and presents you with the new connection screen.  After you fill up the details and press "GO", you get this in logs after a while (and then you are back at the connection screen):

```
2-07 18:03:33.825 23769 23769 E tryToGet: Couldn't execute Get request
12-07 18:03:33.825 23769 23769 E tryToGet: V1.a: Connect timeout has expired [url=<reducted>, connect_timeout=unknown ms]
12-07 18:03:33.825 23769 23769 E tryToGet: 	at W1.v.a(SourceFile:60)
12-07 18:03:33.825 23769 23769 E tryToGet: 	at W1.v.b(SourceFile:6)
12-07 18:03:33.825 23769 23769 E tryToGet: 	at io.ktor.client.engine.cio.h.W(SourceFile:5)
12-07 18:03:33.825 23769 23769 E tryToGet: 	at io.ktor.client.engine.cio.h.E(SourceFile:520)
12-07 18:03:33.825 23769 23769 E tryToGet: 	at io.ktor.client.engine.cio.h.c(SourceFile:1)
12-07 18:03:33.825 23769 23769 E tryToGet: 	at io.ktor.client.engine.cio.h$b.B(SourceFile:1)
12-07 18:03:33.825 23769 23769 E tryToGet: 	at V2.a.l(SourceFile:12)
12-07 18:03:33.825 23769 23769 E tryToGet: 	at t3.B.h1(SourceFile:7)
12-07 18:03:33.825 23769 23769 E tryToGet: 	at o3.a.l(SourceFile:16)
12-07 18:03:33.825 23769 23769 E tryToGet: 	at V2.a.l(SourceFile:48)
12-07 18:03:33.825 23769 23769 E tryToGet: 	at o3.a0.run(SourceFile:115)
12-07 18:03:33.825 23769 23769 E tryToGet: 	at t3.m$a.run(SourceFile:4)
12-07 18:03:33.825 23769 23769 E tryToGet: 	at v3.k.run(SourceFile:3)
12-07 18:03:33.825 23769 23769 E tryToGet: 	at v3.a.D(SourceFile:1)
12-07 18:03:33.825 23769 23769 E tryToGet: 	at v3.a$c.d(SourceFile:15)
12-07 18:03:33.825 23769 23769 E tryToGet: 	at v3.a$c.p(SourceFile:29)
12-07 18:03:33.825 23769 23769 E tryToGet: 	at v3.a$c.run(SourceFile:1)
12-07 18:03:34.130 32606   316 E MiuiFastConnectService: check adv data not fast connect
12-07 18:03:36.087 32606   316 E MiuiFastConnectService: check adv data not fast connect
12-07 18:03:38.786 32606   316 E MiuiFastConnectService: check adv data not fast connect
12-07 18:03:38.833 23769 23769 E tryToGet: Couldn't execute Get request
12-07 18:03:38.833 23769 23769 E tryToGet: V1.a: Connect timeout has expired [url=<reducted>, connect_timeout=unknown ms]
12-07 18:03:38.833 23769 23769 E tryToGet: 	at W1.v.a(SourceFile:60)
12-07 18:03:38.833 23769 23769 E tryToGet: 	at W1.v.b(SourceFile:6)
12-07 18:03:38.833 23769 23769 E tryToGet: 	at io.ktor.client.engine.cio.h.W(SourceFile:5)
12-07 18:03:38.833 23769 23769 E tryToGet: 	at io.ktor.client.engine.cio.h.E(SourceFile:520)
12-07 18:03:38.833 23769 23769 E tryToGet: 	at io.ktor.client.engine.cio.h.c(SourceFile:1)
12-07 18:03:38.833 23769 23769 E tryToGet: 	at io.ktor.client.engine.cio.h$b.B(SourceFile:1)
12-07 18:03:38.833 23769 23769 E tryToGet: 	at V2.a.l(SourceFile:12)
12-07 18:03:38.833 23769 23769 E tryToGet: 	at t3.B.h1(SourceFile:7)
12-07 18:03:38.833 23769 23769 E tryToGet: 	at o3.a.l(SourceFile:16)
12-07 18:03:38.833 23769 23769 E tryToGet: 	at V2.a.l(SourceFile:48)
12-07 18:03:38.833 23769 23769 E tryToGet: 	at o3.a0.run(SourceFile:115)
12-07 18:03:38.833 23769 23769 E tryToGet: 	at t3.m$a.run(SourceFile:4)
12-07 18:03:38.833 23769 23769 E tryToGet: 	at v3.k.run(SourceFile:3)
12-07 18:03:38.833 23769 23769 E tryToGet: 	at v3.a.D(SourceFile:1)
12-07 18:03:38.833 23769 23769 E tryToGet: 	at v3.a$c.d(SourceFile:15)
12-07 18:03:38.833 23769 23769 E tryToGet: 	at v3.a$c.p(SourceFile:29)
12-07 18:03:38.833 23769 23769 E tryToGet: 	at v3.a$c.run(SourceFile:1)
```

**Comment by cmm** [comment]
[ ... moar ]

> Looking at the [commit log](https://gitea.amine-bouabdallaoui.fr/Louvorg/ReaderForSelfoss-multiplatform/commits/branch/master), all of the last few changelogs have been only updated after the corresponding version was released. Perhaps this is a limitation of the automatic Fastlane workflow.

Yes, and you may notice that all those recent changes are just chores.

**Comment by aminecmi** [comment]
@cmm sorry for the email issue. Your account is now activated.

I'm looking into the issue.
